// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Init();
}

public class BitmapFont
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr BitmapFont_Create();
    public BitmapFont() { _native = BitmapFont_Create(); }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr BitmapFont_CharWidth(IntPtr instance);
    public IntPtr CharWidth()
    {
        return BitmapFont_CharWidth(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern int BitmapFont_CharHeight(IntPtr instance);
    public int CharHeight()
    {
        return BitmapFont_CharHeight(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr BitmapFont_GetGlyph(IntPtr instance, sbyte c);
    public IntPtr GetGlyph(sbyte c)
    {
        return BitmapFont_GetGlyph(_native, c);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void BitmapFont_Init(IntPtr instance);
    public void Init()
    {
        BitmapFont_Init(_native);
    }
}
