// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.GPU;

public static class NativeBindings_ColorUtil
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr FromRgba(byte r, byte g, byte b, byte a);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern byte A(uint argb);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern byte R(uint argb);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern byte G(uint argb);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern byte B(uint argb);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern uint Blend(uint src, uint dst);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr FromRgba_1(IntPtr arg0, IntPtr arg1, IntPtr arg2, IntPtr arg3);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern uint Multiply(uint color, uint tint);
}

public static class ColorUtil
{

    // ── Marshal helpers ────────────────────────────────────────────────────────
    private static System.IntPtr MarshalString(string? s)
    {
        if (s is null) return System.IntPtr.Zero;
        return System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(s);
    }
    private static void FreeNative(System.IntPtr p)
    {
        if (p != System.IntPtr.Zero)
            System.Runtime.InteropServices.Marshal.FreeCoTaskMem(p);
    }
    private static string MarshalPtrToString(System.IntPtr p)
    {
        if (p == System.IntPtr.Zero) return string.Empty;
        return System.Runtime.InteropServices.Marshal.PtrToStringUTF8(p) ?? string.Empty;
    }
    private static byte[] MarshalPtrToByteArray(System.IntPtr ptr, System.UIntPtr size)
    {
        if (ptr == System.IntPtr.Zero || (ulong)size == 0UL) return System.Array.Empty<byte>();
        var _res = new byte[(int)(ulong)size];
        System.Runtime.InteropServices.Marshal.Copy(ptr, _res, 0, _res.Length);
        return _res;
    }
    // ── End helpers ────────────────────────────────────────────────────────────


    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern uint ColorUtil_FromRgba(byte r, byte g, byte b, byte a);
    public static uint FromRgba(byte r, byte g, byte b, byte a)
    {
        return ColorUtil_FromRgba(r, g, b, a);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern byte ColorUtil_A(uint argb);
    public static byte A(uint argb)
    {
        return ColorUtil_A(argb);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern byte ColorUtil_R(uint argb);
    public static byte R(uint argb)
    {
        return ColorUtil_R(argb);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern byte ColorUtil_G(uint argb);
    public static byte G(uint argb)
    {
        return ColorUtil_G(argb);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern byte ColorUtil_B(uint argb);
    public static byte B(uint argb)
    {
        return ColorUtil_B(argb);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern uint ColorUtil_Blend(uint src, uint dst);
    public static uint Blend(uint src, uint dst)
    {
        return ColorUtil_Blend(src, dst);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern uint ColorUtil_Multiply(uint color, uint tint);
    public static uint Multiply(uint color, uint tint)
    {
        return ColorUtil_Multiply(color, tint);
    }
}
