// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr FromRgba(IntPtr r, IntPtr g, IntPtr b, IntPtr a);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr A(IntPtr argb);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr R(IntPtr argb);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr G(IntPtr argb);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr B(IntPtr argb);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Blend(IntPtr src, IntPtr dst);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr FromRgba_1(IntPtr arg0, IntPtr arg1, IntPtr arg2, IntPtr arg3);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Multiply(IntPtr color, IntPtr tint);
}

public class ColorUtil
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr ColorUtil_FromRgba(IntPtr instance, IntPtr r, IntPtr g, IntPtr b, IntPtr a);
    public IntPtr FromRgba(IntPtr r, IntPtr g, IntPtr b, IntPtr a)
    {
        return ColorUtil_FromRgba(_native, r, g, b, a);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr ColorUtil_A(IntPtr instance, IntPtr argb);
    public IntPtr A(IntPtr argb)
    {
        return ColorUtil_A(_native, argb);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr ColorUtil_R(IntPtr instance, IntPtr argb);
    public IntPtr R(IntPtr argb)
    {
        return ColorUtil_R(_native, argb);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr ColorUtil_G(IntPtr instance, IntPtr argb);
    public IntPtr G(IntPtr argb)
    {
        return ColorUtil_G(_native, argb);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr ColorUtil_B(IntPtr instance, IntPtr argb);
    public IntPtr B(IntPtr argb)
    {
        return ColorUtil_B(_native, argb);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr ColorUtil_Blend(IntPtr instance, IntPtr src, IntPtr dst);
    public IntPtr Blend(IntPtr src, IntPtr dst)
    {
        return ColorUtil_Blend(_native, src, dst);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr ColorUtil_FromRgba(IntPtr instance, IntPtr unnamed, IntPtr unnamed, IntPtr unnamed, IntPtr unnamed);
    public IntPtr FromRgba(IntPtr unnamed, IntPtr unnamed, IntPtr unnamed, IntPtr unnamed)
    {
        return ColorUtil_FromRgba(_native, unnamed, unnamed, unnamed, unnamed);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr ColorUtil_Multiply(IntPtr instance, IntPtr color, IntPtr tint);
    public IntPtr Multiply(IntPtr color, IntPtr tint)
    {
        return ColorUtil_Multiply(_native, color, tint);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr ColorUtil_FromRgba(IntPtr instance, IntPtr tr);
    public IntPtr FromRgba(IntPtr tr)
    {
        return ColorUtil_FromRgba(_native, tr);
    }
}
