// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Clear();
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Add(IntPtr cmd);
}

[StructLayout(LayoutKind.Sequential)]
public struct ICommand
{
    public IntPtr _ICommand__;
}

[StructLayout(LayoutKind.Sequential)]
public struct DrawQuadCall
{
    public IntPtr texture;
    public int x;
    public int y;
    public int width;
    public int height;
    public IntPtr tint;
}

public class CommandBuffer
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr CommandBuffer_Clear(IntPtr instance);
    public IntPtr Clear()
    {
        return CommandBuffer_Clear(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void CommandBuffer_Add(IntPtr instance, IntPtr cmd);
    public void Add(IntPtr cmd)
    {
        CommandBuffer_Add(_native, cmd);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr CommandBuffer_Commands(IntPtr instance);
    public IntPtr Commands()
    {
        return CommandBuffer_Commands(_native);
    }
}
