// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.GPU;

public static class NativeBindings_CommandBuffer
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Clear();
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Add(IntPtr cmd);
}

[StructLayout(LayoutKind.Sequential)]
public struct ICommand
{
    public IntPtr _ICommand__;
}

[StructLayout(LayoutKind.Sequential)]
public struct DrawQuadCall
{
    public IntPtr texture;
    public int x;
    public int y;
    public int width;
    public int height;
    public uint tint;
}

public class CommandBuffer
{
    private IntPtr _native;
    /// <summary>Exposes the raw native handle for interop use.</summary>
    public IntPtr _Handle => _native;

    // ── Marshal helpers ────────────────────────────────────────────────────────
    private static System.IntPtr MarshalString(string? s)
    {
        if (s is null) return System.IntPtr.Zero;
        return System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(s);
    }
    private static void FreeNative(System.IntPtr p)
    {
        if (p != System.IntPtr.Zero)
            System.Runtime.InteropServices.Marshal.FreeCoTaskMem(p);
    }
    private static string MarshalPtrToString(System.IntPtr p)
    {
        if (p == System.IntPtr.Zero) return string.Empty;
        return System.Runtime.InteropServices.Marshal.PtrToStringUTF8(p) ?? string.Empty;
    }
    private static byte[] MarshalPtrToByteArray(System.IntPtr ptr, System.UIntPtr size)
    {
        if (ptr == System.IntPtr.Zero || (ulong)size == 0UL) return System.Array.Empty<byte>();
        var _res = new byte[(int)(ulong)size];
        System.Runtime.InteropServices.Marshal.Copy(ptr, _res, 0, _res.Length);
        return _res;
    }
    // ── End helpers ────────────────────────────────────────────────────────────


    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr CommandBuffer_Create();
    /// <summary>Creates a new native instance via the default constructor.</summary>
    public CommandBuffer() { _native = CommandBuffer_Create(); }
    /// <summary>Wraps an existing native pointer. Does not take ownership.</summary>
    public CommandBuffer(IntPtr nativeHandle) { _native = nativeHandle; }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void CommandBuffer_Clear(IntPtr instance);
    public void Clear()
    {
        CommandBuffer_Clear(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void CommandBuffer_Add(IntPtr instance, IntPtr cmd);
    public void Add(IntPtr cmd)
    {
        CommandBuffer_Add(_native, cmd);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr CommandBuffer_Commands(IntPtr instance);
    public IntPtr Commands()
    {
        return CommandBuffer_Commands(_native);
    }
}
