// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.GPU;

public static class NativeBindings_IRenderBackend
{
}

[StructLayout(LayoutKind.Sequential)]
public struct Rect
{
    public int X;
    public int Y;
    public int W;
    public int H;
}

public class IRenderBackend
{
    private IntPtr _native;
    /// <summary>Exposes the raw native handle for interop use.</summary>
    public IntPtr _Handle => _native;

    // ── Marshal helpers ────────────────────────────────────────────────────────
    private static System.IntPtr MarshalString(string? s)
    {
        if (s is null) return System.IntPtr.Zero;
        return System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(s);
    }
    private static void FreeNative(System.IntPtr p)
    {
        if (p != System.IntPtr.Zero)
            System.Runtime.InteropServices.Marshal.FreeCoTaskMem(p);
    }
    private static string MarshalPtrToString(System.IntPtr p)
    {
        if (p == System.IntPtr.Zero) return string.Empty;
        return System.Runtime.InteropServices.Marshal.PtrToStringUTF8(p) ?? string.Empty;
    }
    private static byte[] MarshalPtrToByteArray(System.IntPtr ptr, System.UIntPtr size)
    {
        if (ptr == System.IntPtr.Zero || (ulong)size == 0UL) return System.Array.Empty<byte>();
        var _res = new byte[(int)(ulong)size];
        System.Runtime.InteropServices.Marshal.Copy(ptr, _res, 0, _res.Length);
        return _res;
    }
    // ── End helpers ────────────────────────────────────────────────────────────


    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr IRenderBackend_Create();
    /// <summary>Creates a new native instance via the default constructor.</summary>
    public IRenderBackend() { _native = IRenderBackend_Create(); }
    /// <summary>Wraps an existing native pointer. Does not take ownership.</summary>
    public IRenderBackend(IntPtr nativeHandle) { _native = nativeHandle; }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IRenderBackend_Initialize(IntPtr instance, IntPtr engine, IntPtr canvas);
    public void Initialize(IntPtr engine, IntPtr canvas)
    {
        IRenderBackend_Initialize(_native, engine, canvas);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IRenderBackend_Upload(IntPtr instance, IntPtr canvas, IntPtr regions);
    public void Upload(IntPtr canvas, IntPtr regions)
    {
        IRenderBackend_Upload(_native, canvas, regions);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IRenderBackend_Present(IntPtr instance);
    public void Present()
    {
        IRenderBackend_Present(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern bool IRenderBackend_PumpEvents(IntPtr instance);
    public bool PumpEvents()
    {
        return IRenderBackend_PumpEvents(_native);
    }
}
