// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
}

[StructLayout(LayoutKind.Sequential)]
public struct Rect
{
    public int X;
    public int Y;
    public int W;
    public int H;
}

public class IRenderBackend
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr IRenderBackend_Initialize(IntPtr instance, IntPtr engine, IntPtr canvas);
    public IntPtr Initialize(IntPtr engine, IntPtr canvas)
    {
        return IRenderBackend_Initialize(_native, engine, canvas);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr IRenderBackend_Upload(IntPtr instance, IntPtr canvas, IntPtr regions);
    public IntPtr Upload(IntPtr canvas, IntPtr regions)
    {
        return IRenderBackend_Upload(_native, canvas, regions);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr IRenderBackend_Present(IntPtr instance);
    public IntPtr Present()
    {
        return IRenderBackend_Present(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr IRenderBackend_PumpEvents(IntPtr instance);
    public IntPtr PumpEvents()
    {
        return IRenderBackend_PumpEvents(_native);
    }
}
