// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.GPU;

public static class NativeBindings_IRenderBackend
{
}

[StructLayout(LayoutKind.Sequential)]
public struct Rect
{
    public int X;
    public int Y;
    public int W;
    public int H;
}

public class IRenderBackend
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IRenderBackend_Initialize(IntPtr instance, IntPtr engine, IntPtr canvas);
    public void Initialize(IntPtr engine, IntPtr canvas)
    {
        IRenderBackend_Initialize(_native, engine, canvas);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IRenderBackend_Upload(IntPtr instance, IntPtr canvas, IntPtr regions);
    public void Upload(IntPtr canvas, IntPtr regions)
    {
        IRenderBackend_Upload(_native, canvas, regions);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IRenderBackend_Present(IntPtr instance);
    public void Present()
    {
        IRenderBackend_Present(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern bool IRenderBackend_PumpEvents(IntPtr instance);
    public bool PumpEvents()
    {
        return IRenderBackend_PumpEvents(_native);
    }
}
