// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.GPU;

public static class NativeBindings_Renderer
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Target();
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr CmdBuffer();
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Clear(uint color);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void FillRect(int x, int y, int w, int h, uint color);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawSurface(IntPtr src, int x, int y);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawQuad(IntPtr texture, int x, int y, int w, int h, uint tint);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Submit();
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawText(IntPtr text, int x, int y, uint color);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawChar(sbyte c, int x, int y, uint color);
}

public class Renderer
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr Renderer_Create(IntPtr target);
    public Renderer(IntPtr target) { _native = Renderer_Create(target); }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr Renderer_Target(IntPtr instance);
    public IntPtr Target()
    {
        return Renderer_Target(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr Renderer_Font(IntPtr instance);
    public IntPtr Font()
    {
        return Renderer_Font(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr Renderer_CmdBuffer(IntPtr instance);
    public IntPtr CmdBuffer()
    {
        return Renderer_CmdBuffer(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Renderer_Clear(IntPtr instance, uint color);
    public void Clear(uint color)
    {
        Renderer_Clear(_native, color);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Renderer_FillRect(IntPtr instance, int x, int y, int w, int h, uint color);
    public void FillRect(int x, int y, int w, int h, uint color)
    {
        Renderer_FillRect(_native, x, y, w, h, color);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Renderer_DrawSurface(IntPtr instance, IntPtr src, int x, int y);
    public void DrawSurface(IntPtr src, int x, int y)
    {
        Renderer_DrawSurface(_native, src, x, y);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Renderer_DrawQuad(IntPtr instance, IntPtr texture, int x, int y, int w, int h, uint tint);
    public void DrawQuad(IntPtr texture, int x, int y, int w, int h, uint tint)
    {
        Renderer_DrawQuad(_native, texture, x, y, w, h, tint);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Renderer_Submit(IntPtr instance);
    public void Submit()
    {
        Renderer_Submit(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Renderer_DrawText(IntPtr instance, IntPtr text, int x, int y, uint color);
    public void DrawText(IntPtr text, int x, int y, uint color)
    {
        Renderer_DrawText(_native, text, x, y, color);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Renderer_DrawChar(IntPtr instance, sbyte c, int x, int y, uint color);
    public void DrawChar(sbyte c, int x, int y, uint color)
    {
        Renderer_DrawChar(_native, c, x, y, color);
    }
}
