// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.GPU;

public static class NativeBindings_SDLAdapterRenderer
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Target();
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr CmdBuffer();
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Clear(uint color);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void FillRect(int x, int y, int w, int h, uint color);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawSurface(IntPtr src, int x, int y);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawQuad(IntPtr texture, int x, int y, int w, int h, uint tint);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Submit();
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawText(IntPtr text, int x, int y, uint color);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawChar(sbyte c, int x, int y, uint color);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Shutdown();
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Dispose();
}

public class SDLAdapterRenderer
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr SDLAdapterRenderer_Target(IntPtr instance);
    public IntPtr Target()
    {
        return SDLAdapterRenderer_Target(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr SDLAdapterRenderer_Font(IntPtr instance);
    public IntPtr Font()
    {
        return SDLAdapterRenderer_Font(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr SDLAdapterRenderer_CmdBuffer(IntPtr instance);
    public IntPtr CmdBuffer()
    {
        return SDLAdapterRenderer_CmdBuffer(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void SDLAdapterRenderer_Initialize(IntPtr instance, IntPtr arg0, IntPtr arg1);
    public void Initialize(IntPtr arg0, IntPtr arg1)
    {
        SDLAdapterRenderer_Initialize(_native, arg0, arg1);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void SDLAdapterRenderer_Upload(IntPtr instance, IntPtr arg0, IntPtr arg1);
    public void Upload(IntPtr arg0, IntPtr arg1)
    {
        SDLAdapterRenderer_Upload(_native, arg0, arg1);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void SDLAdapterRenderer_Present(IntPtr instance);
    public void Present()
    {
        SDLAdapterRenderer_Present(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern bool SDLAdapterRenderer_PumpEvents(IntPtr instance);
    public bool PumpEvents()
    {
        return SDLAdapterRenderer_PumpEvents(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void SDLAdapterRenderer_Clear(IntPtr instance, uint color);
    public void Clear(uint color)
    {
        SDLAdapterRenderer_Clear(_native, color);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void SDLAdapterRenderer_FillRect(IntPtr instance, int x, int y, int w, int h, uint color);
    public void FillRect(int x, int y, int w, int h, uint color)
    {
        SDLAdapterRenderer_FillRect(_native, x, y, w, h, color);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void SDLAdapterRenderer_DrawSurface(IntPtr instance, IntPtr src, int x, int y);
    public void DrawSurface(IntPtr src, int x, int y)
    {
        SDLAdapterRenderer_DrawSurface(_native, src, x, y);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void SDLAdapterRenderer_DrawQuad(IntPtr instance, IntPtr texture, int x, int y, int w, int h, uint tint);
    public void DrawQuad(IntPtr texture, int x, int y, int w, int h, uint tint)
    {
        SDLAdapterRenderer_DrawQuad(_native, texture, x, y, w, h, tint);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void SDLAdapterRenderer_Submit(IntPtr instance);
    public void Submit()
    {
        SDLAdapterRenderer_Submit(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void SDLAdapterRenderer_DrawText(IntPtr instance, IntPtr text, int x, int y, uint color);
    public void DrawText(IntPtr text, int x, int y, uint color)
    {
        SDLAdapterRenderer_DrawText(_native, text, x, y, color);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void SDLAdapterRenderer_DrawChar(IntPtr instance, sbyte c, int x, int y, uint color);
    public void DrawChar(sbyte c, int x, int y, uint color)
    {
        SDLAdapterRenderer_DrawChar(_native, c, x, y, color);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void SDLAdapterRenderer_Shutdown(IntPtr instance);
    public void Shutdown()
    {
        SDLAdapterRenderer_Shutdown(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void SDLAdapterRenderer_Dispose(IntPtr instance);
    public void Dispose()
    {
        SDLAdapterRenderer_Dispose(_native);
    }
}
