// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.GPU;

public static class NativeBindings_SimpleGPURunner
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr _target(IntPtr arg0);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Execute(IntPtr cb);
}

public class SimpleGPURunner
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr SimpleGPURunner_Create(IntPtr target);
    public SimpleGPURunner(IntPtr target) { _native = SimpleGPURunner_Create(target); }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void SimpleGPURunner_Execute(IntPtr instance, IntPtr cb);
    public void Execute(IntPtr cb)
    {
        SimpleGPURunner_Execute(_native, cb);
    }
}
