// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Pixels();
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Clear(IntPtr color);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void SetPixel(int x, int y, IntPtr color);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void FillRect(int x, int y, int w, int h, IntPtr color);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Blit(IntPtr src, int dstX, int dstY);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawTexturedQuad(IntPtr texture, int dstX, int dstY, int dstW, int dstH, IntPtr tint);
}

public class Surface
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr Surface_Create(int width, int height);
    public Surface() { _native = Surface_Create(); }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr Surface_Width(IntPtr instance);
    public IntPtr Width()
    {
        return Surface_Width(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern int Surface_Height(IntPtr instance);
    public int Height()
    {
        return Surface_Height(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr Surface_Pixels(IntPtr instance);
    public IntPtr Pixels()
    {
        return Surface_Pixels(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr Surface_Pixels(IntPtr instance);
    public IntPtr Pixels()
    {
        return Surface_Pixels(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Surface_Clear(IntPtr instance, IntPtr color);
    public void Clear(IntPtr color)
    {
        Surface_Clear(_native, color);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Surface_SetPixel(IntPtr instance, int x, int y, IntPtr color);
    public void SetPixel(int x, int y, IntPtr color)
    {
        Surface_SetPixel(_native, x, y, color);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr Surface_GetPixel(IntPtr instance, int x, int y);
    public IntPtr GetPixel(int x, int y)
    {
        return Surface_GetPixel(_native, x, y);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Surface_FillRect(IntPtr instance, int x, int y, int w, int h, IntPtr color);
    public void FillRect(int x, int y, int w, int h, IntPtr color)
    {
        Surface_FillRect(_native, x, y, w, h, color);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Surface_Blit(IntPtr instance, IntPtr src, int dstX, int dstY);
    public void Blit(IntPtr src, int dstX, int dstY)
    {
        Surface_Blit(_native, src, dstX, dstY);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Surface_DrawTexturedQuad(IntPtr instance, IntPtr texture, int dstX, int dstY, int dstW, int dstH, IntPtr tint);
    public void DrawTexturedQuad(IntPtr texture, int dstX, int dstY, int dstW, int dstH, IntPtr tint)
    {
        Surface_DrawTexturedQuad(_native, texture, dstX, dstY, dstW, dstH, tint);
    }
}
