// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.GPU;

public static class NativeBindings_Texture
{
}

public class Texture
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr Texture_Create(IntPtr surface);
    public Texture(IntPtr surface) { _native = Texture_Create(surface); }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr Texture_SurfacePtr(IntPtr instance);
    public IntPtr SurfacePtr()
    {
        return Texture_SurfacePtr(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern int Texture_Width(IntPtr instance);
    public int Width()
    {
        return Texture_Width(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern int Texture_Height(IntPtr instance);
    public int Height()
    {
        return Texture_Height(_native);
    }
}
