// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.GPU;

public static class NativeBindings_VirtualTerminal
{

    // ── Marshal helpers ────────────────────────────────────────────────────────
    private static System.IntPtr MarshalString(string? s)
    {
        if (s is null) return System.IntPtr.Zero;
        return System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(s);
    }
    private static void FreeNative(System.IntPtr p)
    {
        if (p != System.IntPtr.Zero)
            System.Runtime.InteropServices.Marshal.FreeCoTaskMem(p);
    }
    private static string MarshalPtrToString(System.IntPtr p)
    {
        if (p == System.IntPtr.Zero) return string.Empty;
        return System.Runtime.InteropServices.Marshal.PtrToStringUTF8(p) ?? string.Empty;
    }
    private static byte[] MarshalPtrToByteArray(System.IntPtr ptr, System.UIntPtr size)
    {
        if (ptr == System.IntPtr.Zero || (ulong)size == 0UL) return System.Array.Empty<byte>();
        var _res = new byte[(int)(ulong)size];
        System.Runtime.InteropServices.Marshal.Copy(ptr, _res, 0, _res.Length);
        return _res;
    }
    // ── End helpers ────────────────────────────────────────────────────────────

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Default();
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Clear();
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Resize(int columns, int rows);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl, EntryPoint = "nc")]
    private static extern IntPtr nc_Extern(IntPtr columns, IntPtr _, out UIntPtr _outSize);
    public static byte[] nc(IntPtr columns, IntPtr _)
    {
        var _ptr = nc_Extern(columns, _, out var _outSize);
        return MarshalPtrToByteArray(_ptr, _outSize);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr nf(IntPtr columns, IntPtr arg1);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr nb(IntPtr columns, IntPtr arg1);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl, EntryPoint = "Write")]
    private static extern void Write_Extern(IntPtr text);
    public static void Write(string text)
    {
        var _raw_text = MarshalString(text);
        Write_Extern(_raw_text);
        FreeNative(_raw_text);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr PutChar(IntPtr arg0);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl, EntryPoint = "WriteLine")]
    private static extern void WriteLine_Extern(IntPtr text);
    public static void WriteLine(string text)
    {
        var _raw_text = MarshalString(text);
        WriteLine_Extern(_raw_text);
        FreeNative(_raw_text);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void PutChar_1(sbyte c);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl, EntryPoint = "PutStringAt")]
    private static extern void PutStringAt_Extern(IntPtr text, int x, int y, uint fg, uint bg);
    public static void PutStringAt(string text, int x, int y, uint fg, uint bg)
    {
        var _raw_text = MarshalString(text);
        PutStringAt_Extern(_raw_text, x, y, fg, bg);
        FreeNative(_raw_text);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl, EntryPoint = "RenderToSurface")]
    private static extern void RenderToSurface_Extern(IntPtr surface);
    public static void RenderToSurface(Surface surface)
    {
        var _raw_surface = surface._Handle;
        RenderToSurface_Extern(_raw_surface);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void RenderToCanvas(IntPtr canvas);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ScrollUp(int lines);
}

public class VirtualTerminal
{
    private IntPtr _native;
    /// <summary>Exposes the raw native handle for interop use.</summary>
    public IntPtr _Handle => _native;

    // ── Marshal helpers ────────────────────────────────────────────────────────
    private static System.IntPtr MarshalString(string? s)
    {
        if (s is null) return System.IntPtr.Zero;
        return System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(s);
    }
    private static void FreeNative(System.IntPtr p)
    {
        if (p != System.IntPtr.Zero)
            System.Runtime.InteropServices.Marshal.FreeCoTaskMem(p);
    }
    private static string MarshalPtrToString(System.IntPtr p)
    {
        if (p == System.IntPtr.Zero) return string.Empty;
        return System.Runtime.InteropServices.Marshal.PtrToStringUTF8(p) ?? string.Empty;
    }
    private static byte[] MarshalPtrToByteArray(System.IntPtr ptr, System.UIntPtr size)
    {
        if (ptr == System.IntPtr.Zero || (ulong)size == 0UL) return System.Array.Empty<byte>();
        var _res = new byte[(int)(ulong)size];
        System.Runtime.InteropServices.Marshal.Copy(ptr, _res, 0, _res.Length);
        return _res;
    }
    // ── End helpers ────────────────────────────────────────────────────────────


    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr VirtualTerminal_Create();
    /// <summary>Creates a new native instance via the default constructor.</summary>
    public VirtualTerminal() { _native = VirtualTerminal_Create(); }
    /// <summary>Wraps an existing native pointer. Does not take ownership.</summary>
    public VirtualTerminal(IntPtr nativeHandle) { _native = nativeHandle; }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern int VirtualTerminal_Columns(IntPtr instance);
    public int Columns()
    {
        return VirtualTerminal_Columns(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern int VirtualTerminal_Rows(IntPtr instance);
    public int Rows()
    {
        return VirtualTerminal_Rows(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern int VirtualTerminal_CursorX(IntPtr instance);
    public int CursorX()
    {
        return VirtualTerminal_CursorX(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern int VirtualTerminal_CursorY(IntPtr instance);
    public int CursorY()
    {
        return VirtualTerminal_CursorY(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void VirtualTerminal_Clear(IntPtr instance);
    public void Clear()
    {
        VirtualTerminal_Clear(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void VirtualTerminal_Resize(IntPtr instance, int columns, int rows);
    public void Resize(int columns, int rows)
    {
        VirtualTerminal_Resize(_native, columns, rows);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void VirtualTerminal_Write(IntPtr instance, IntPtr text);
    public void Write(string text)
    {
        var _raw_text = MarshalString(text);
        VirtualTerminal_Write(_native, _raw_text);
        FreeNative(_raw_text);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void VirtualTerminal_WriteLine(IntPtr instance, IntPtr text);
    public void WriteLine(string text)
    {
        var _raw_text = MarshalString(text);
        VirtualTerminal_WriteLine(_native, _raw_text);
        FreeNative(_raw_text);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void VirtualTerminal_PutChar(IntPtr instance, sbyte c);
    public void PutChar(sbyte c)
    {
        VirtualTerminal_PutChar(_native, c);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void VirtualTerminal_PutStringAt(IntPtr instance, IntPtr text, int x, int y, uint fg, uint bg);
    public void PutStringAt(string text, int x, int y, uint fg, uint bg)
    {
        var _raw_text = MarshalString(text);
        VirtualTerminal_PutStringAt(_native, _raw_text, x, y, fg, bg);
        FreeNative(_raw_text);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr VirtualTerminal_GetCurrentLine(IntPtr instance);
    public string GetCurrentLine()
    {
        var _ret = VirtualTerminal_GetCurrentLine(_native);
        return MarshalPtrToString(_ret);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void VirtualTerminal_RenderToSurface(IntPtr instance, IntPtr surface);
    public void RenderToSurface(Surface surface)
    {
        var _raw_surface = surface._Handle;
        VirtualTerminal_RenderToSurface(_native, _raw_surface);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void VirtualTerminal_RenderToCanvas(IntPtr instance, IntPtr canvas);
    public void RenderToCanvas(IntPtr canvas)
    {
        VirtualTerminal_RenderToCanvas(_native, canvas);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void VirtualTerminal_ScrollUp(IntPtr instance, int lines);
    public void ScrollUp(int lines)
    {
        VirtualTerminal_ScrollUp(_native, lines);
    }
}
