// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr DrawRect(IntPtr c, int x, int y, int w, int h, IntPtr color);
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr DrawLine(IntPtr c, int x0, int y0, int x1, int y1, IntPtr color);
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr DrawOutlinedRect(IntPtr c, int x, int y, int w, int h, IntPtr color);
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawText(IntPtr c, int x, int y, IntPtr text, IntPtr color);
}
