namespace Adamantite.BindingGenerator
{
    public class Program
    {
        public const string Version = "0.1.0";
        public const string RepoUrl = "https://github.com/fy-nite/Adamantite";
        public const string HeaderContent = @"// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: ${RepoUrl}
// Version: ${Version}
        ";

        public static string[] Directories = [
            "../Adamantite.Core/",
            "../Adamantite.Cpp/",
            "../Adamantite.html/",
            "../Adamantite.video/",
            "../Adamantite.runtime/",
            "../Adamantite.audio/"
        ];
        public const string OutputDirectory = "../Adamantite.CSharp.Bindings/src/";
        public static void Main(string[] args)
        {
            Console.WriteLine($"Adamantite Binding Generator - Version {Version}");
            Console.WriteLine($"Repo: {RepoUrl}");
            Console.WriteLine("Generating bindings...");

            foreach (var directory in Directories)
            {
                Console.WriteLine($"Processing directory: {directory}");
                var generator = new BindingGenerator(directory, OutputDirectory, HeaderContent);
                generator.GenerateBindings();
            }

            Console.WriteLine("Binding generation completed.");
        }
    }
}
