// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Target();
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr CmdBuffer();
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Clear(IntPtr color);
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern void FillRect(int x, int y, int w, int h, IntPtr color);
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawSurface(IntPtr src, int x, int y);
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawQuad(IntPtr texture, int x, int y, int w, int h, IntPtr tint);
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Submit();
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawText(IntPtr text, int x, int y, IntPtr color);
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawChar(sbyte c, int x, int y, IntPtr color);
}
