// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.Util;

public static class NativeBindings_DebugUtil
{
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Debug(IntPtr msg);
}

public class DebugUtil
{
    private IntPtr _native;

    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr DebugUtil_Debug(IntPtr instance, IntPtr msg);
    public IntPtr Debug(IntPtr msg)
    {
        return DebugUtil_Debug(_native, msg);
    }
}
