// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Emit(IntPtr level, IntPtr header, IntPtr contents, IntPtr callStack);
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Info(IntPtr header, IntPtr contents, IntPtr callStack);
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Warning(IntPtr header, IntPtr contents, IntPtr callStack);
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Error(IntPtr header, IntPtr contents, IntPtr callStack);
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Debug(IntPtr header, IntPtr contents, IntPtr callStack);
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr LevelName(IntPtr level);
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr LevelColor(IntPtr level);
    [DllImport("NativeLib.dll", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr EnableVirtualTerminal();
}
