// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void TriggerClick();
}

public class Button
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr Button_UIElement(IntPtr instance, IntPtr unnamed);
    public IntPtr UIElement(IntPtr unnamed)
    {
        return Button_UIElement(_native, unnamed);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Button_TriggerClick(IntPtr instance);
    public void TriggerClick()
    {
        Button_TriggerClick(_native);
    }
}
