// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.UI;

public static class NativeBindings_Button
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void TriggerClick();
}

public class Button
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Button_Draw(IntPtr instance, IntPtr canvas, IntPtr arg1);
    public void Draw(IntPtr canvas, IntPtr arg1)
    {
        Button_Draw(_native, canvas, arg1);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Button_TriggerClick(IntPtr instance);
    public void TriggerClick()
    {
        Button_TriggerClick(_native);
    }
}
