// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.UI;

public static class NativeBindings_Label
{
}

public class Label
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Label_Draw(IntPtr instance, IntPtr canvas, IntPtr arg1);
    public void Draw(IntPtr canvas, IntPtr arg1)
    {
        Label_Draw(_native, canvas, arg1);
    }
}
