// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using Adamantite;
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.UI;

public static class NativeBindings_Label
{
}

public class Label
{
    private IntPtr _native;
    /// <summary>Exposes the raw native handle for interop use.</summary>
    public IntPtr _Handle => _native;

    // ── Marshal helpers ────────────────────────────────────────────────────────
    private static System.IntPtr MarshalString(string? s)
    {
        if (s is null) return System.IntPtr.Zero;
        return System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(s);
    }
    private static void FreeNative(System.IntPtr p)
    {
        if (p != System.IntPtr.Zero)
            System.Runtime.InteropServices.Marshal.FreeCoTaskMem(p);
    }
    private static string MarshalPtrToString(System.IntPtr p)
    {
        if (p == System.IntPtr.Zero) return string.Empty;
        return System.Runtime.InteropServices.Marshal.PtrToStringUTF8(p) ?? string.Empty;
    }
    private static byte[] MarshalPtrToByteArray(System.IntPtr ptr, System.UIntPtr size)
    {
        if (ptr == System.IntPtr.Zero || (ulong)size == 0UL) return System.Array.Empty<byte>();
        var _res = new byte[(int)(ulong)size];
        System.Runtime.InteropServices.Marshal.Copy(ptr, _res, 0, _res.Length);
        return _res;
    }
    // ── End helpers ────────────────────────────────────────────────────────────


    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr Label_Create();
    /// <summary>Creates a new native instance via the default constructor.</summary>
    public Label() { _native = Label_Create(); }
    /// <summary>Wraps an existing native pointer. Does not take ownership.</summary>
    public Label(IntPtr nativeHandle) { _native = nativeHandle; }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Label_Draw(IntPtr instance, IntPtr canvas, IntPtr arg1);
    public void Draw(Canvas canvas, IntPtr arg1)
    {
        var _raw_canvas = canvas._Handle;
        Label_Draw(_native, _raw_canvas, arg1);
    }
}
