// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Intersect(IntPtr a, IntPtr b);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Union(IntPtr a, IntPtr b);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Bounds(IntPtr arg0);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Invalidate(IntPtr area);
}

[StructLayout(LayoutKind.Sequential)]
public struct Rect
{
    public int X;
    public int Y;
    public int Width;
    public int Height;
    public int y;
    public int b_Y_;
    public int r;
    public int b_Right___;
    public int bot;
    public int b_Bottom___;
    public IntPtr _;
    public IntPtr y;
    public IntPtr _0;
    public IntPtr _0_;
    public IntPtr _x;
    public IntPtr y;
    public IntPtr x;
    public IntPtr y_;
    public int y;
    public int b_Y_;
    public int r;
    public int b_Right___;
    public int bot;
    public int b_Bottom___;
    public IntPtr _x;
    public IntPtr y;
    public IntPtr x;
    public IntPtr y_;
}

public class UIManager
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr UIManager_UIElement(IntPtr instance, IntPtr bounds);
    public IntPtr UIElement(IntPtr bounds)
    {
        return UIManager_UIElement(_native, bounds);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr UIManager_Draw(IntPtr instance, IntPtr canvas, IntPtr clip);
    public IntPtr Draw(IntPtr canvas, IntPtr clip)
    {
        return UIManager_Draw(_native, canvas, clip);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void UIManager_Invalidate(IntPtr instance, IntPtr area);
    public void Invalidate(IntPtr area)
    {
        UIManager_Invalidate(_native, area);
    }
}
