// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.UI;

public static class NativeBindings_UIElement
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Intersect(IntPtr a, IntPtr b);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Union(IntPtr a, IntPtr b);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Bounds(IntPtr arg0);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Invalidate(IntPtr area);
}

[StructLayout(LayoutKind.Sequential)]
public struct Rect
{
    public int X;
    public int Y;
    public int Width;
    public int Height;
}

public class UIElement
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr UIElement_Create(IntPtr bounds);
    public UIElement(IntPtr bounds) { _native = UIElement_Create(bounds); }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void UIElement_Draw(IntPtr instance, IntPtr canvas, IntPtr clip);
    public void Draw(IntPtr canvas, IntPtr clip)
    {
        UIElement_Draw(_native, canvas, clip);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void UIElement_Invalidate(IntPtr instance, IntPtr area);
    public void Invalidate(IntPtr area)
    {
        UIElement_Invalidate(_native, area);
    }
}
