// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using Adamantite;
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.UI;

public static class NativeBindings_UIManager
{

    // ── Marshal helpers ────────────────────────────────────────────────────────
    private static System.IntPtr MarshalString(string? s)
    {
        if (s is null) return System.IntPtr.Zero;
        return System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(s);
    }
    private static void FreeNative(System.IntPtr p)
    {
        if (p != System.IntPtr.Zero)
            System.Runtime.InteropServices.Marshal.FreeCoTaskMem(p);
    }
    private static string MarshalPtrToString(System.IntPtr p)
    {
        if (p == System.IntPtr.Zero) return string.Empty;
        return System.Runtime.InteropServices.Marshal.PtrToStringUTF8(p) ?? string.Empty;
    }
    private static byte[] MarshalPtrToByteArray(System.IntPtr ptr, System.UIntPtr size)
    {
        if (ptr == System.IntPtr.Zero || (ulong)size == 0UL) return System.Array.Empty<byte>();
        var _res = new byte[(int)(ulong)size];
        System.Runtime.InteropServices.Marshal.Copy(ptr, _res, 0, _res.Length);
        return _res;
    }
    // ── End helpers ────────────────────────────────────────────────────────────

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl, EntryPoint = "Add")]
    private static extern IntPtr Add_Extern(IntPtr e);
    public static IntPtr Add(UIElement e)
    {
        var _raw_e = e._Handle;
        return Add_Extern(_raw_e);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl, EntryPoint = "Remove")]
    private static extern void Remove_Extern(IntPtr e);
    public static void Remove(UIElement e)
    {
        var _raw_e = e._Handle;
        Remove_Extern(_raw_e);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void NotifyInvalid(IntPtr r);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl, EntryPoint = "RenderDirty")]
    private static extern IntPtr RenderDirty_Extern(IntPtr canvas);
    public static IntPtr RenderDirty(Canvas canvas)
    {
        var _raw_canvas = canvas._Handle;
        return RenderDirty_Extern(_raw_canvas);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ProcessInputAt(int mx, int my, bool mouseReleased);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr CoalesceDirty();
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr list(IntPtr arg0);
}

public class UIManager
{
    private IntPtr _native;
    /// <summary>Exposes the raw native handle for interop use.</summary>
    public IntPtr _Handle => _native;

    // ── Marshal helpers ────────────────────────────────────────────────────────
    private static System.IntPtr MarshalString(string? s)
    {
        if (s is null) return System.IntPtr.Zero;
        return System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(s);
    }
    private static void FreeNative(System.IntPtr p)
    {
        if (p != System.IntPtr.Zero)
            System.Runtime.InteropServices.Marshal.FreeCoTaskMem(p);
    }
    private static string MarshalPtrToString(System.IntPtr p)
    {
        if (p == System.IntPtr.Zero) return string.Empty;
        return System.Runtime.InteropServices.Marshal.PtrToStringUTF8(p) ?? string.Empty;
    }
    private static byte[] MarshalPtrToByteArray(System.IntPtr ptr, System.UIntPtr size)
    {
        if (ptr == System.IntPtr.Zero || (ulong)size == 0UL) return System.Array.Empty<byte>();
        var _res = new byte[(int)(ulong)size];
        System.Runtime.InteropServices.Marshal.Copy(ptr, _res, 0, _res.Length);
        return _res;
    }
    // ── End helpers ────────────────────────────────────────────────────────────


    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr UIManager_Create();
    /// <summary>Creates a new native instance via the default constructor.</summary>
    public UIManager() { _native = UIManager_Create(); }
    /// <summary>Wraps an existing native pointer. Does not take ownership.</summary>
    public UIManager(IntPtr nativeHandle) { _native = nativeHandle; }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void UIManager_Add(IntPtr instance, IntPtr e);
    public void Add(UIElement e)
    {
        var _raw_e = e._Handle;
        UIManager_Add(_native, _raw_e);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void UIManager_Remove(IntPtr instance, IntPtr e);
    public void Remove(UIElement e)
    {
        var _raw_e = e._Handle;
        UIManager_Remove(_native, _raw_e);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void UIManager_NotifyInvalid(IntPtr instance, IntPtr r);
    public void NotifyInvalid(IntPtr r)
    {
        UIManager_NotifyInvalid(_native, r);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr UIManager_RenderDirty(IntPtr instance, IntPtr canvas);
    public IntPtr RenderDirty(Canvas canvas)
    {
        var _raw_canvas = canvas._Handle;
        return UIManager_RenderDirty(_native, _raw_canvas);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void UIManager_ProcessInputAt(IntPtr instance, int mx, int my, bool mouseReleased);
    public void ProcessInputAt(int mx, int my, bool mouseReleased)
    {
        UIManager_ProcessInputAt(_native, mx, my, mouseReleased);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr UIManager_CoalesceDirty(IntPtr instance);
    public IntPtr CoalesceDirty()
    {
        return UIManager_CoalesceDirty(_native);
    }
}
