// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Add(IntPtr e);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Remove(IntPtr e);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void NotifyInvalid(IntPtr r);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr RenderDirty(IntPtr canvas);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ProcessInputAt(int mx, int my, bool mouseReleased);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr CoalesceDirty();
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr list(IntPtr arg0);
}

public class UIManager
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr UIManager_Add(IntPtr instance, IntPtr e);
    public IntPtr Add(IntPtr e)
    {
        return UIManager_Add(_native, e);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void UIManager_Remove(IntPtr instance, IntPtr e);
    public void Remove(IntPtr e)
    {
        UIManager_Remove(_native, e);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void UIManager_NotifyInvalid(IntPtr instance, IntPtr r);
    public void NotifyInvalid(IntPtr r)
    {
        UIManager_NotifyInvalid(_native, r);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr UIManager_RenderDirty(IntPtr instance, IntPtr canvas);
    public IntPtr RenderDirty(IntPtr canvas)
    {
        return UIManager_RenderDirty(_native, canvas);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr UIManager_if(IntPtr instance, IntPtr unnamed);
    public IntPtr if(IntPtr unnamed)
    {
        return UIManager_if(_native, unnamed);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void UIManager_ProcessInputAt(IntPtr instance, int mx, int my, bool mouseReleased);
    public void ProcessInputAt(int mx, int my, bool mouseReleased)
    {
        UIManager_ProcessInputAt(_native, mx, my, mouseReleased);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr UIManager_CoalesceDirty(IntPtr instance);
    public IntPtr CoalesceDirty()
    {
        return UIManager_CoalesceDirty(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr UIManager_list(IntPtr instance, IntPtr unnamed);
    public IntPtr list(IntPtr unnamed)
    {
        return UIManager_list(_native, unnamed);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr UIManager_if(IntPtr instance, IntPtr unnamed);
    public IntPtr if(IntPtr unnamed)
    {
        return UIManager_if(_native, unnamed);
    }
}
