// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.Renderers;

public static class NativeBindings_RendererStubs
{

    // ── Marshal helpers ────────────────────────────────────────────────────────
    private static System.IntPtr MarshalString(string? s)
    {
        if (s is null) return System.IntPtr.Zero;
        return System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(s);
    }
    private static void FreeNative(System.IntPtr p)
    {
        if (p != System.IntPtr.Zero)
            System.Runtime.InteropServices.Marshal.FreeCoTaskMem(p);
    }
    private static string MarshalPtrToString(System.IntPtr p)
    {
        if (p == System.IntPtr.Zero) return string.Empty;
        return System.Runtime.InteropServices.Marshal.PtrToStringUTF8(p) ?? string.Empty;
    }
    private static byte[] MarshalPtrToByteArray(System.IntPtr ptr, System.UIntPtr size)
    {
        if (ptr == System.IntPtr.Zero || (ulong)size == 0UL) return System.Array.Empty<byte>();
        var _res = new byte[(int)(ulong)size];
        System.Runtime.InteropServices.Marshal.Copy(ptr, _res, 0, _res.Length);
        return _res;
    }
    // ── End helpers ────────────────────────────────────────────────────────────

    [DllImport("Adamantite.core", CallingConvention = CallingConvention.Cdecl, EntryPoint = "CreateSDLRenderer")]
    private static extern IntPtr CreateSDLRenderer_Extern();
    public static IRenderer CreateSDLRenderer()
    {
        var _ret = CreateSDLRenderer_Extern();
        return new IRenderer(_ret);
    }
}

public class IRenderer
{
    private IntPtr _native;
    /// <summary>Exposes the raw native handle for interop use.</summary>
    public IntPtr _Handle => _native;

    // ── Marshal helpers ────────────────────────────────────────────────────────
    private static System.IntPtr MarshalString(string? s)
    {
        if (s is null) return System.IntPtr.Zero;
        return System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(s);
    }
    private static void FreeNative(System.IntPtr p)
    {
        if (p != System.IntPtr.Zero)
            System.Runtime.InteropServices.Marshal.FreeCoTaskMem(p);
    }
    private static string MarshalPtrToString(System.IntPtr p)
    {
        if (p == System.IntPtr.Zero) return string.Empty;
        return System.Runtime.InteropServices.Marshal.PtrToStringUTF8(p) ?? string.Empty;
    }
    private static byte[] MarshalPtrToByteArray(System.IntPtr ptr, System.UIntPtr size)
    {
        if (ptr == System.IntPtr.Zero || (ulong)size == 0UL) return System.Array.Empty<byte>();
        var _res = new byte[(int)(ulong)size];
        System.Runtime.InteropServices.Marshal.Copy(ptr, _res, 0, _res.Length);
        return _res;
    }
    // ── End helpers ────────────────────────────────────────────────────────────


    [DllImport("Adamantite.core", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr IRenderer_Create();
    /// <summary>Creates a new native instance via the default constructor.</summary>
    public IRenderer() { _native = IRenderer_Create(); }
    /// <summary>Wraps an existing native pointer. Does not take ownership.</summary>
    public IRenderer(IntPtr nativeHandle) { _native = nativeHandle; }
    [DllImport("Adamantite.core", CallingConvention = CallingConvention.Cdecl)]
    private static extern bool IRenderer_Init(IntPtr instance, int width, int height, IntPtr title);
    public bool Init(int width, int height, IntPtr title)
    {
        return IRenderer_Init(_native, width, height, title);
    }
    [DllImport("Adamantite.core", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IRenderer_BeginFrame(IntPtr instance);
    public void BeginFrame()
    {
        IRenderer_BeginFrame(_native);
    }
    [DllImport("Adamantite.core", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IRenderer_EndFrame(IntPtr instance);
    public void EndFrame()
    {
        IRenderer_EndFrame(_native);
    }
    [DllImport("Adamantite.core", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IRenderer_Clear(IntPtr instance, float r, float g, float b, float a);
    public void Clear(float r, float g, float b, float a)
    {
        IRenderer_Clear(_native, r, g, b, a);
    }
    [DllImport("Adamantite.core", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IRenderer_Shutdown(IntPtr instance);
    public void Shutdown()
    {
        IRenderer_Shutdown(_native);
    }
}
