// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.Renderers;

public static class NativeBindings_RendererStubs
{
    [DllImport("Adamantite.core", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr CreateSDLRenderer();
}

public class IRenderer
{
    private IntPtr _native;

    [DllImport("Adamantite.core", CallingConvention = CallingConvention.Cdecl)]
    private static extern bool IRenderer_Init(IntPtr instance, int width, int height, IntPtr title);
    public bool Init(int width, int height, IntPtr title)
    {
        return IRenderer_Init(_native, width, height, title);
    }
    [DllImport("Adamantite.core", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IRenderer_BeginFrame(IntPtr instance);
    public void BeginFrame()
    {
        IRenderer_BeginFrame(_native);
    }
    [DllImport("Adamantite.core", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IRenderer_EndFrame(IntPtr instance);
    public void EndFrame()
    {
        IRenderer_EndFrame(_native);
    }
    [DllImport("Adamantite.core", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IRenderer_Clear(IntPtr instance, float r, float g, float b, float a);
    public void Clear(float r, float g, float b, float a)
    {
        IRenderer_Clear(_native, r, g, b, a);
    }
    [DllImport("Adamantite.core", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IRenderer_Shutdown(IntPtr instance);
    public void Shutdown()
    {
        IRenderer_Shutdown(_native);
    }
}
