// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings;

public static class NativeBindings_CanvasTextHelper
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Prin(IntPtr c, int x, int y, IntPtr text, IntPtr color);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GetGlyphs();
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawText(IntPtr c, int x, int y, IntPtr text, IntPtr color);
}

public class CanvasTextHelper
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void CanvasTextHelper_Prin(IntPtr instance, IntPtr c, int x, int y, IntPtr text, IntPtr color);
    public void Prin(IntPtr c, int x, int y, IntPtr text, IntPtr color)
    {
        CanvasTextHelper_Prin(_native, c, x, y, text, color);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr CanvasTextHelper_GetGlyphs(IntPtr instance);
    public IntPtr GetGlyphs()
    {
        return CanvasTextHelper_GetGlyphs(_native);
    }
}
