// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings;

public static class NativeBindings_CanvasExtensions
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawRect(IntPtr c, int x, int y, int w, int h, IntPtr color);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawLine(IntPtr c, int x0, int y0, int x1, int y1, IntPtr color);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawOutlinedRect(IntPtr c, int x, int y, int w, int h, IntPtr color);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawText(IntPtr c, int x, int y, IntPtr text, IntPtr color);
}
