// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace Adamantite;

public static class NativeBindings_CanvasTextHelper
{

    // ── Marshal helpers ────────────────────────────────────────────────────────
    private static System.IntPtr MarshalString(string? s)
    {
        if (s is null) return System.IntPtr.Zero;
        return System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(s);
    }
    private static void FreeNative(System.IntPtr p)
    {
        if (p != System.IntPtr.Zero)
            System.Runtime.InteropServices.Marshal.FreeCoTaskMem(p);
    }
    private static string MarshalPtrToString(System.IntPtr p)
    {
        if (p == System.IntPtr.Zero) return string.Empty;
        return System.Runtime.InteropServices.Marshal.PtrToStringUTF8(p) ?? string.Empty;
    }
    private static byte[] MarshalPtrToByteArray(System.IntPtr ptr, System.UIntPtr size)
    {
        if (ptr == System.IntPtr.Zero || (ulong)size == 0UL) return System.Array.Empty<byte>();
        var _res = new byte[(int)(ulong)size];
        System.Runtime.InteropServices.Marshal.Copy(ptr, _res, 0, _res.Length);
        return _res;
    }
    // ── End helpers ────────────────────────────────────────────────────────────

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl, EntryPoint = "Prin")]
    private static extern void Prin_Extern(IntPtr c, int x, int y, IntPtr text, IntPtr color);
    public static void Prin(Canvas c, int x, int y, string text, IntPtr color)
    {
        var _raw_c = c._Handle;
        var _raw_text = MarshalString(text);
        Prin_Extern(_raw_c, x, y, _raw_text, color);
        FreeNative(_raw_text);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GetGlyphs();
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl, EntryPoint = "DrawText")]
    private static extern void DrawText_Extern(IntPtr c, int x, int y, IntPtr text, IntPtr color);
    public static void DrawText(Canvas c, int x, int y, string text, IntPtr color)
    {
        var _raw_c = c._Handle;
        var _raw_text = MarshalString(text);
        DrawText_Extern(_raw_c, x, y, _raw_text, color);
        FreeNative(_raw_text);
    }
}

public class CanvasTextHelper
{
    private IntPtr _native;
    /// <summary>Exposes the raw native handle for interop use.</summary>
    public IntPtr _Handle => _native;

    // ── Marshal helpers ────────────────────────────────────────────────────────
    private static System.IntPtr MarshalString(string? s)
    {
        if (s is null) return System.IntPtr.Zero;
        return System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(s);
    }
    private static void FreeNative(System.IntPtr p)
    {
        if (p != System.IntPtr.Zero)
            System.Runtime.InteropServices.Marshal.FreeCoTaskMem(p);
    }
    private static string MarshalPtrToString(System.IntPtr p)
    {
        if (p == System.IntPtr.Zero) return string.Empty;
        return System.Runtime.InteropServices.Marshal.PtrToStringUTF8(p) ?? string.Empty;
    }
    private static byte[] MarshalPtrToByteArray(System.IntPtr ptr, System.UIntPtr size)
    {
        if (ptr == System.IntPtr.Zero || (ulong)size == 0UL) return System.Array.Empty<byte>();
        var _res = new byte[(int)(ulong)size];
        System.Runtime.InteropServices.Marshal.Copy(ptr, _res, 0, _res.Length);
        return _res;
    }
    // ── End helpers ────────────────────────────────────────────────────────────


    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr CanvasTextHelper_Create();
    /// <summary>Creates a new native instance via the default constructor.</summary>
    public CanvasTextHelper() { _native = CanvasTextHelper_Create(); }
    /// <summary>Wraps an existing native pointer. Does not take ownership.</summary>
    public CanvasTextHelper(IntPtr nativeHandle) { _native = nativeHandle; }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void CanvasTextHelper_Prin(IntPtr c, int x, int y, IntPtr text, IntPtr color);
    public static void Prin(Canvas c, int x, int y, string text, IntPtr color)
    {
        var _raw_c = c._Handle;
        var _raw_text = MarshalString(text);
        CanvasTextHelper_Prin(_raw_c, x, y, _raw_text, color);
        FreeNative(_raw_text);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr CanvasTextHelper_GetGlyphs();
    public static IntPtr GetGlyphs()
    {
        return CanvasTextHelper_GetGlyphs();
    }
}
