// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace Adamantite;

public static class NativeBindings_Canvas
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Clear(IntPtr c);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void SetPixel(int x, int y, IntPtr c);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawFilledRect(int startX, int startY, int w, int h, IntPtr c);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr ColorFromLong(long value);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void MarkDirtyRect(int x, int y, int w, int h);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ClearDirty();
}

[StructLayout(LayoutKind.Sequential)]
public struct Color
{
    public byte r;
    public byte g;
    public byte b;
    public byte a;
    public IntPtr White;
    public IntPtr Black;
}

public class Canvas
{
    private IntPtr _native;
    /// <summary>Exposes the raw native handle for interop use.</summary>
    public IntPtr _Handle => _native;

    // ── Marshal helpers ────────────────────────────────────────────────────────
    private static System.IntPtr MarshalString(string? s)
    {
        if (s is null) return System.IntPtr.Zero;
        return System.Runtime.InteropServices.Marshal.StringToCoTaskMemUTF8(s);
    }
    private static void FreeNative(System.IntPtr p)
    {
        if (p != System.IntPtr.Zero)
            System.Runtime.InteropServices.Marshal.FreeCoTaskMem(p);
    }
    private static string MarshalPtrToString(System.IntPtr p)
    {
        if (p == System.IntPtr.Zero) return string.Empty;
        return System.Runtime.InteropServices.Marshal.PtrToStringUTF8(p) ?? string.Empty;
    }
    private static byte[] MarshalPtrToByteArray(System.IntPtr ptr, System.UIntPtr size)
    {
        if (ptr == System.IntPtr.Zero || (ulong)size == 0UL) return System.Array.Empty<byte>();
        var _res = new byte[(int)(ulong)size];
        System.Runtime.InteropServices.Marshal.Copy(ptr, _res, 0, _res.Length);
        return _res;
    }
    // ── End helpers ────────────────────────────────────────────────────────────


    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr Canvas_Create();
    /// <summary>Creates a new native instance via the default constructor.</summary>
    public Canvas() { _native = Canvas_Create(); }
    /// <summary>Wraps an existing native pointer. Does not take ownership.</summary>
    public Canvas(IntPtr nativeHandle) { _native = nativeHandle; }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Canvas_Clear(IntPtr instance, IntPtr c);
    public void Clear(IntPtr c)
    {
        Canvas_Clear(_native, c);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Canvas_SetPixel(IntPtr instance, int x, int y, IntPtr c);
    public void SetPixel(int x, int y, IntPtr c)
    {
        Canvas_SetPixel(_native, x, y, c);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Canvas_DrawFilledRect(IntPtr instance, int startX, int startY, int w, int h, IntPtr c);
    public void DrawFilledRect(int startX, int startY, int w, int h, IntPtr c)
    {
        Canvas_DrawFilledRect(_native, startX, startY, w, h, c);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr Canvas_ColorFromLong(long value);
    public static IntPtr ColorFromLong(long value)
    {
        return Canvas_ColorFromLong(value);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Canvas_MarkDirtyRect(IntPtr instance, int x, int y, int w, int h);
    public void MarkDirtyRect(int x, int y, int w, int h)
    {
        Canvas_MarkDirtyRect(_native, x, y, w, h);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Canvas_ClearDirty(IntPtr instance);
    public void ClearDirty()
    {
        Canvas_ClearDirty(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern bool Canvas_IsDirty(IntPtr instance);
    public bool IsDirty()
    {
        return Canvas_IsDirty(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern int Canvas_DirtyX(IntPtr instance);
    public int DirtyX()
    {
        return Canvas_DirtyX(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern int Canvas_DirtyY(IntPtr instance);
    public int DirtyY()
    {
        return Canvas_DirtyY(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern int Canvas_DirtyWidth(IntPtr instance);
    public int DirtyWidth()
    {
        return Canvas_DirtyWidth(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern int Canvas_DirtyHeight(IntPtr instance);
    public int DirtyHeight()
    {
        return Canvas_DirtyHeight(_native);
    }
}
