// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Clear(IntPtr c);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void SetPixel(int x, int y, IntPtr c);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void DrawFilledRect(int startX, int startY, int w, int h, IntPtr c);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr ColorFromLong(long value);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void MarkDirtyRect(int x, int y, int w, int h);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ClearDirty();
}

[StructLayout(LayoutKind.Sequential)]
public struct Color
{
    public IntPtr r;
    public IntPtr g;
    public IntPtr b;
    public IntPtr a;
    public IntPtr Black;
}

public class Canvas
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Canvas_Clear(IntPtr instance, IntPtr c);
    public void Clear(IntPtr c)
    {
        Canvas_Clear(_native, c);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Canvas_SetPixel(IntPtr instance, int x, int y, IntPtr c);
    public void SetPixel(int x, int y, IntPtr c)
    {
        Canvas_SetPixel(_native, x, y, c);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Canvas_DrawFilledRect(IntPtr instance, int startX, int startY, int w, int h, IntPtr c);
    public void DrawFilledRect(int startX, int startY, int w, int h, IntPtr c)
    {
        Canvas_DrawFilledRect(_native, startX, startY, w, h, c);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr Canvas_ColorFromLong(IntPtr instance, long value);
    public IntPtr ColorFromLong(long value)
    {
        return Canvas_ColorFromLong(_native, value);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Canvas_MarkDirtyRect(IntPtr instance, int x, int y, int w, int h);
    public void MarkDirtyRect(int x, int y, int w, int h)
    {
        Canvas_MarkDirtyRect(_native, x, y, w, h);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void Canvas_ClearDirty(IntPtr instance);
    public void ClearDirty()
    {
        Canvas_ClearDirty(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern bool Canvas_IsDirty(IntPtr instance);
    public bool IsDirty()
    {
        return Canvas_IsDirty(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern int Canvas_DirtyX(IntPtr instance);
    public int DirtyX()
    {
        return Canvas_DirtyX(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern int Canvas_DirtyY(IntPtr instance);
    public int DirtyY()
    {
        return Canvas_DirtyY(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern int Canvas_DirtyWidth(IntPtr instance);
    public int DirtyWidth()
    {
        return Canvas_DirtyWidth(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern int Canvas_DirtyHeight(IntPtr instance);
    public int DirtyHeight()
    {
        return Canvas_DirtyHeight(_native);
    }
}
