// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace Adamantite;

public static class NativeBindings_Colors
{
}

[StructLayout(LayoutKind.Sequential)]
public struct Colors
{
    public IntPtr White;
    public IntPtr Black;
    public IntPtr Gray;
    public IntPtr DarkGray;
    public IntPtr Cyan;
    public IntPtr Magenta;
    public IntPtr Yellow;
    public IntPtr Orange;
    public IntPtr Green;
    public IntPtr DarkGreen;
}
