// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings;

public static class NativeBindings_FpsCounter
{
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Tick(double elapsedSeconds);
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Reset();
}

public class FpsCounter
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr FpsCounter_Create();
    public FpsCounter() { _native = FpsCounter_Create(); }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern double FpsCounter_Fps(IntPtr instance);
    public double Fps()
    {
        return FpsCounter_Fps(_native);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void FpsCounter_Tick(IntPtr instance, double elapsedSeconds);
    public void Tick(double elapsedSeconds)
    {
        FpsCounter_Tick(_native, elapsedSeconds);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void FpsCounter_Reset(IntPtr instance);
    public void Reset()
    {
        FpsCounter_Reset(_native);
    }
}
