// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
}

public class IConsoleGame
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr IConsoleGame_Init(IntPtr instance, IntPtr surface);
    public IntPtr Init(IntPtr surface)
    {
        return IConsoleGame_Init(_native, surface);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr IConsoleGame_Update(IntPtr instance, double deltaTime);
    public IntPtr Update(double deltaTime)
    {
        return IConsoleGame_Update(_native, deltaTime);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr IConsoleGame_Draw(IntPtr instance, IntPtr surface);
    public IntPtr Draw(IntPtr surface)
    {
        return IConsoleGame_Draw(_native, surface);
    }
}
