// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings;

public static class NativeBindings_IConsoleGame
{
}

public class IConsoleGame
{
    private IntPtr _native;

    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IConsoleGame_Init(IntPtr instance, IntPtr surface);
    public void Init(IntPtr surface)
    {
        IConsoleGame_Init(_native, surface);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IConsoleGame_Update(IntPtr instance, double deltaTime);
    public void Update(double deltaTime)
    {
        IConsoleGame_Update(_native, deltaTime);
    }
    [DllImport("Adamantite.video", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IConsoleGame_Draw(IntPtr instance, IntPtr surface);
    public void Draw(IntPtr surface)
    {
        IConsoleGame_Draw(_native, surface);
    }
}
