// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("Adamantite.Core", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr SetLogLevel(IntPtr level);
    [DllImport("Adamantite.Core", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GetLogLevel();
    [DllImport("Adamantite.Core", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr ParseLogLevel(IntPtr str);
    [DllImport("Adamantite.Core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Info(IntPtr message);
    [DllImport("Adamantite.Core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Warning(IntPtr message);
    [DllImport("Adamantite.Core", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Error(IntPtr message);
}
