// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Register();
}

public class NativeConnectors
{
    private IntPtr _native;

    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr NativeConnectors_Register(IntPtr instance);
    public IntPtr Register()
    {
        return NativeConnectors_Register(_native);
    }
}
