// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.VFS;

public static class NativeBindings_IFileSystem
{
}

public class IFileSystem
{
    private IntPtr _native;

    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr IFileSystem_ReadAllBytes(IntPtr instance, IntPtr path);
    public IntPtr ReadAllBytes(IntPtr path)
    {
        return IFileSystem_ReadAllBytes(_native, path);
    }
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IFileSystem_WriteAllBytes(IntPtr instance, IntPtr path, IntPtr data);
    public void WriteAllBytes(IntPtr path, IntPtr data)
    {
        IFileSystem_WriteAllBytes(_native, path, data);
    }
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern bool IFileSystem_Exists(IntPtr instance, IntPtr path);
    public bool Exists(IntPtr path)
    {
        return IFileSystem_Exists(_native, path);
    }
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr IFileSystem_Enumerate(IntPtr instance, IntPtr path);
    public IntPtr Enumerate(IntPtr path)
    {
        return IFileSystem_Enumerate(_native, path);
    }
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr IFileSystem_GetFileInfo(IntPtr instance, IntPtr path);
    public IntPtr GetFileInfo(IntPtr path)
    {
        return IFileSystem_GetFileInfo(_native, path);
    }
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IFileSystem_CreateDirectory(IntPtr instance, IntPtr path);
    public void CreateDirectory(IntPtr path)
    {
        IFileSystem_CreateDirectory(_native, path);
    }
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern void IFileSystem_Delete(IntPtr instance, IntPtr path);
    public void Delete(IntPtr path)
    {
        IFileSystem_Delete(_native, path);
    }
}
