// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr lock(IntPtr arg0);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr lock(IntPtr arg0);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr lock(IntPtr arg0);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr lock(IntPtr arg0);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr lock(IntPtr arg0);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr lock(IntPtr arg0);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr lock(IntPtr arg0);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern void CreateSymlink(IntPtr linkPath, IntPtr targetPath);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Normalize(IntPtr path);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Normalize(IntPtr arg0);
}
