// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;
namespace AdamantiteBindings.VFS;

public static class NativeBindings_PhysicalFileSystem
{
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr PhysicalFileSystem(IntPtr rootPath);
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr f(IntPtr arg0, IntPtr arg1);
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr f_1(IntPtr arg0, IntPtr std__ios__trunc);
}

public class PhysicalFileSystem
{
    private IntPtr _native;

    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr PhysicalFileSystem_Create(IntPtr rootPath);
    public PhysicalFileSystem(IntPtr rootPath) { _native = PhysicalFileSystem_Create(rootPath); }
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr PhysicalFileSystem_ReadAllBytes(IntPtr instance, IntPtr path);
    public IntPtr ReadAllBytes(IntPtr path)
    {
        return PhysicalFileSystem_ReadAllBytes(_native, path);
    }
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern void PhysicalFileSystem_WriteAllBytes(IntPtr instance, IntPtr path, IntPtr data);
    public void WriteAllBytes(IntPtr path, IntPtr data)
    {
        PhysicalFileSystem_WriteAllBytes(_native, path, data);
    }
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern bool PhysicalFileSystem_Exists(IntPtr instance, IntPtr path);
    public bool Exists(IntPtr path)
    {
        return PhysicalFileSystem_Exists(_native, path);
    }
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr PhysicalFileSystem_Enumerate(IntPtr instance, IntPtr path);
    public IntPtr Enumerate(IntPtr path)
    {
        return PhysicalFileSystem_Enumerate(_native, path);
    }
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr PhysicalFileSystem_GetFileInfo(IntPtr instance, IntPtr path);
    public IntPtr GetFileInfo(IntPtr path)
    {
        return PhysicalFileSystem_GetFileInfo(_native, path);
    }
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern void PhysicalFileSystem_CreateDirectory(IntPtr instance, IntPtr path);
    public void CreateDirectory(IntPtr path)
    {
        PhysicalFileSystem_CreateDirectory(_native, path);
    }
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern void PhysicalFileSystem_Delete(IntPtr instance, IntPtr path);
    public void Delete(IntPtr path)
    {
        PhysicalFileSystem_Delete(_native, path);
    }
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr PhysicalFileSystem_ToPhysical(IntPtr instance, IntPtr path);
    public IntPtr ToPhysical(IntPtr path)
    {
        return PhysicalFileSystem_ToPhysical(_native, path);
    }
}
