// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr LoadFont(IntPtr vfs, IntPtr fontPath);
}

public class VfsFontLoader
{
    private IntPtr _native;

    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr VfsFontLoader_LoadFont(IntPtr instance, IntPtr vfs, IntPtr fontPath);
    public IntPtr LoadFont(IntPtr vfs, IntPtr fontPath)
    {
        return VfsFontLoader_LoadFont(_native, vfs, fontPath);
    }
}
