// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Manager();
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr SetManager(IntPtr manager);
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Initialize();
}

public class VFSGlobal
{
    private IntPtr _native;

    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr VFSGlobal_Manager(IntPtr instance);
    public IntPtr Manager()
    {
        return VFSGlobal_Manager(_native);
    }
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr VFSGlobal_SetManager(IntPtr instance, IntPtr manager);
    public IntPtr SetManager(IntPtr manager)
    {
        return VFSGlobal_SetManager(_native, manager);
    }
    [DllImport("Adamantite.cpp", CallingConvention = CallingConvention.Cdecl)]
    private static extern IntPtr VFSGlobal_Initialize(IntPtr instance);
    public IntPtr Initialize()
    {
        return VFSGlobal_Initialize(_native);
    }
}
