// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Mount(IntPtr mountPoint, IntPtr fs);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Unmount(IntPtr mountPoint);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr ReadAllBytes(IntPtr path);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern void WriteAllBytes(IntPtr path, IntPtr data);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern bool Exists(IntPtr path);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern bool FileExists(IntPtr path);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Exists(IntPtr arg0);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Enumerate(IntPtr path);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GetFileInfo(IntPtr path);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern void CreateDirectory(IntPtr path);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Delete(IntPtr path);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Remove(IntPtr path);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr NormalizeMountPoint(IntPtr mp);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Resolve(IntPtr path);
}
