// This file is auto-generated by Adamantite Binding Generator.
// Do not edit this file manually. Instead, edit the source C++ headers and regenerate the bindings.
// For more information, visit the Adamantite repository:
// Repo: https://github.com/fy-nite/Adamantite
// Version: 0.1.0
using System;
using System.Runtime.InteropServices;

public static class NativeBindings
{
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr Add(IntPtr e);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern void Remove(IntPtr e);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern void NotifyInvalid(IntPtr r);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr RenderDirty(IntPtr canvas);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern void ProcessInputAt(int mx, int my, bool mouseReleased);
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr CoalesceDirty();
    [DllImport("Adamantite.Cpp", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr list(IntPtr arg0);
}
